added dither
charlypoirier/emojicon pull request #4
Opened 2022-04-09 14:38 UTC by 1Euro7Cent

I also fixed that test module being in production dependencies. Modules like that are usually in devDependencies

You need to update that Firefox logo in the README if you want.

And sorry again for auto formatting

2022-06-17 21:07 UTC, charlypoirier requested changes
Hello,

I've added a few suggestions before merging your pull request.
Also, the code formatting actually looks a bit better now.

Thanks for your help! 🙂

2022-06-17 21:38 UTC, 1Euro7Cent commented on index.js
> +// @ts-nocheck
I use typescript checking and i cannot resolve a error on that line (it works how it is). That disables checking for that line below

2022-06-17 21:40 UTC, 1Euro7Cent commented
Im gonna resolve the rest when i am on my pc

2022-06-17 21:42 UTC, 1Euro7Cent commented on index.js
> +// @ts-nocheck
Ughh ts nocheck disables the checking for the whole file

2022-06-18 10:34 UTC, 1Euro7Cent commented on index.js
> +// @ts-nocheck
if i remove the tsnocheck this happens: 
![image](https://user-images.githubusercontent.com/67194495/174433922-0e1b4c9e-2265-4087-971d-f1474186c5b1.png)
  but ill remove it

2022-06-19 17:29 UTC, 1Euro7Cent commented
I don't know if you noticed it but I resolved it

2022-06-27 18:28 UTC, charlypoirier approved these changes

2022-06-27 18:43 UTC, charlypoirier commented
One last issue, I get this error when trying to launch Emojicon.

```error
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './baseDither'
Require stack:
- /.../projects/emojicon-dev/node_modules/multidither/classes/dither/FloydSteinbergDither.js
- /.../projects/emojicon-dev/node_modules/multidither/index.js
- /.../projects/emojicon-dev/index.js
- ...
```

I think it is because it is trying to import `baseDither.js` but the real file is named `BaseDither.js`.
Do you think you could fix that?

2022-06-27 18:50 UTC, 1Euro7Cent commented
for me it works now

2022-06-27 19:01 UTC, merged

2022-06-27 19:04 UTC, charlypoirier commented
Thanks!